apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: sales-pipeline
description: Canary deployment pipeline for sales prediction app
serialPipeline:
  stages:
    - targetId: dev
      strategy:
        canary:
          runtimeConfig:
            cloudRun:
              automaticTrafficControl: true
          canaryDeployment:
            percentages: [25, 75, 100]
            verify: true
