steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/ml-sales-prediction:$SHORT_SHA', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/ml-sales-prediction:$SHORT_SHA']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ml-sales-prediction
      - --image=gcr.io/$PROJECT_ID/ml-sales-prediction:$SHORT_SHA
      - --region=us-central1
      - --platform=managed
      - --allow-unauthenticated

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - deploy
      - releases
      - create
      - release-$SHORT_SHA
      - --delivery-pipeline=sales-ml-pipeline
      - --region=us-central1
      - --source=.
      - --deploy-target=dev

images:
  - 'gcr.io/$PROJECT_ID/ml-sales-prediction:$SHORT_SHA'
