options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/ml-sales-repo/ml-sales-prediction', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/ml-sales-repo/ml-sales-prediction']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ml-sales-prediction
      - --image=us-central1-docker.pkg.dev/$PROJECT_ID/ml-sales-repo/ml-sales-prediction
      - --region=us-central1
      - --platform=managed
      - --allow-unauthenticated
