apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: sales-pipeline
description: Pipeline for Sales ML app
serialPipeline:
  stages:
    - targetId: dev
      strategy:
        canary:
          runtimeConfig:
            cloudRun:
              automaticTrafficControl: true
