apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: sales-pipeline
description: Pipeline for Sales Prediction ML app with canary rollout
serialPipeline:
  stages:
    - targetId: dev
      strategy:
        canary:
          runtimeConfig:
            cloudRun:
              automaticTrafficControl: true
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev
description: Dev environment for sales prediction ML app
run:
  location: us-central1
  service: ml-app
