apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: sales-pipeline
description: Deployment pipeline for sales prediction app
serialPipeline:
  stages:
    - targetId: dev
      strategy:
        canary:
          mode: AUTOMATIC_TRAFFIC_CONTROL
          runtimeConfig:
            cloudRun:
              automaticTrafficControl: true

