  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'deploy', 'releases', 'create',
        'release-$(date +%Y%m%d%H%M%S)',
        '--region', 'us-central1',
        '--delivery-pipeline', 'sales-pipeline',
        '--image', 'gcr.io/$PROJECT_ID/ml-sales-prediction',
        '--target', 'dev'
      ]
