steps:
  # Your existing build steps
  # ...
  
  # Trigger Cloud Deploy release
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'deploy',
        'releases',
        'create',
        'release-${SHORT_SHA}',  # Unique release name
        '--delivery-pipeline=sales-pipeline',
        '--region=us-central1',
        '--release-targets=dev',
        '--images=ml-app=gcr.io/$PROJECT_ID/ml-app:$SHORT_SHA'
      ]
